package com.sreenu.accessmodifiers;

public class AccessModifiersdemo2 {

	public static void main(String[] args) {
		

	AccessModifiersDemo accessModifiersDemo = new AccessModifiersDemo();
	accessModifiersDemo.name = "Java";             // accessible by  "Has-A-relationship".....
	accessModifiersDemo.nameMethod();             // accessible by  "Has-A-relationship".....
	accessModifiersDemo.city="Hyderabd";         // accessible by  "Has-A-relationship".....
	accessModifiersDemo.cityMethod();           // accessible by  "Has-A-relationship".....
	accessModifiersDemo.country="India";       // accessible by  "Has-A-relationship".....
	accessModifiersDemo.countryMethod();      // accessible by  "Has-A-relationship".....
	//accessModifiersDemo.address = "Yousufguda"; Not accessible by  "Has-A-relationship".....
	
	//accessModifiersDemo.addressMethod(); Not accessible by  "Has-A-relationship".....
}
}