package com.sreenu.accessmodifiers1;

import com.sreenu.accessmodifiers.AccessModifiersDemo;

public class AccessModifiersDemo3 {

	
	public static void main(String[] args) {
		
		AccessModifiersDemo accessModifiersDemo = new AccessModifiersDemo();
		accessModifiersDemo.name = "Vijay";  // accessible by  "Has-A-relationship".....
		accessModifiersDemo.nameMethod();   // accessible by  "Has-A-relationship".....
		
		
		// accessModifiersDemo.country="Ind";    //Not accessible by  "Has-A-relationship".....
		//accessModifiersDemo.countryMethod(); // Not accessible by  "Has-A-relationship".....
		// accessModifiersDemo.address="Indok";//Not accessible by  "Has-A-relationship".....
		// accessModifiersDemo.addressMethod();// Not accessible by  "Has-A-relationship".....
		// accessModifiersDemo.city="Inddel";// Not accessible by  "Has-A-relationship".....
		// accessModifiersDemo.cityMethod(); //Not accessible by  "Has-A-relationship".....
	}
}
